


export const MajCardEnum = Object.freeze({
    ONE_MAN : 0,
    TWO_MAN : 1,
    THREE_MAN : 2,
    FOUR_MAN : 3,
    FIVE_MAN : 4,
    SIX_MAN : 5,
    SEVEN_MAN : 6,
    EIGHT_MAN : 7,
    NINE_MAN : 8,
    ONE_TONG : 9,
    TWO_TONG : 10,
    THREE_TONG : 11,
    FOUR_TONG : 12,
    FIVE_TONG : 13,
    SIX_TONG : 14,
    SEVEN_TONG : 15,
    EIGHT_TONG : 16,
    NINE_TONG : 17,
    ONE_SAK : 18,
    TWO_SAK : 19,
    THREE_SAK : 20,
    FOUR_SAK : 21,
    FIVE_SAK : 22,
    SIX_SAK : 23,
    SEVEN_SAK : 24,
    EIGHT_SAK : 25,
    NINE_SAK : 26,
    DONG : 27,
    NAM : 28,
    SEO : 29,
    BUK : 30,
    BAEK : 31,
    BAL : 32,
    JOONG : 33
})